title: RedCarpet
author: Junaid Choudhary
email: junaidchoudhary210@gmail.com
description: We lend to those where banks cannot reach.

socialProfiles:
  - type: facebook
    url: https://twitter.com/aerobaticapp
  - type: twitter
    url: https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ
  - type: instagram
    url: https://github.com/aerobaticapp
  - type: dribble
    url: https://github.com/justjunaid