title: RedCarpet
author: Junaid Choudhary
email: junaidchoudhary210@gmail.com
description: We lend to those where banks cannot reach.

navBar:
  links:
    - text: SMART CARD
      url: /ruby_card/
    - text: CAMPUS LEADER
      url: /campus_leader/
    - text: CAREERS
      url: /career/
    - text: ABOUT US
      url: /about/
    - text: CONTACT US
      url: /contact/

socialProfiles:
  - type: facebook
    url: https://twitter.com/aerobaticapp
  - type: twitter
    url: https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ
  - type: instagram
    url: https://github.com/justjunaid
  - type: github
    url: https://github.com/justjunaid